services:
  postgres-db:
    image: postgres:15-alpine
  
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: ticketing_db
      
    ports: 
      - "5433:5432"
    
    volumes:
      - "go-volumes:/var/lib/postgresql/data"

  redis-cache:
    image: redis:7-alpine
    container_name: ticekting-redis
    ports:
      - "6379:6379"


volumes:
  go-volumes:
